<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/*
	$block Convert\CategoriesCollection\Block\Products
*/
?>
<?php 
	$blockId = rand() . time();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$productCollection = $block->getProductCollection();
?>
<div class="product-widget-slider">
	<?php if($block->getTitle()): ?>
	<div class="title-wrapper">
		<h2 class="title"><?= $block->getTitle() ?></h2>
	</div>
	<?php endif ?>

	<?php if($productCollection): ?>
		<div class="clear-margin-owl">
			<div id="product-slider-<?= $blockId ?>" class="products-grid product-collection-slider owl-carousel">
				<?php foreach($productCollection as $_product): ?>
					<?php $_product = $block->getProductById($_product->getId()); ?>
					<div class="product-item-info" data-container="product-grid">
						<?php
						$productImage = $_imagehelper->init($_product, 'category_page_grid')->resize(292, 292)->getUrl();
						$_productNameStripped = $block->stripTags($_product->getName(), null, true);
						?>
						<?php // Product Image ?>
						<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<img alt="<?= $_productNameStripped ?>" src="<?= $productImage ?>" class="product-image-photo"/>
						</a>
						<div class="product details product-item-details">
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
								</a>
							</strong>
							<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
							<?= $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTextSwatch($this->getSwatches())->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
							<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
						</div>
					</div>
				<?php endforeach ?>
			</div>
		</div>
		<script type="text/javascript">
			require([
				'jquery', 
				'carousel',
			],function(jQuery){
				jQuery(document).ready(function(){
					jQuery('#product-slider-<?= $blockId ?>').owlCarousel({
						items: 4,
						loop:false,
						margin:0,
						nav:true,
						dots:false,
						responsive:{
							0:{
								items:1
							},
							600:{
								items:3
							},
							992:{
								items:4
							}
						}
					})
				});
			});
		</script>
	<?php endif ?>
</div>