<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php 
		$image = 'category_page_grid';
		$showDescription = true;
	?>
	 <div class="products wrapper products-events">
        <ol class="products list items event-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
				<li class="event-item">
					<div class="event-item-info">
						<?php 
						$productImage = $_imagehelper->init($_product, 'category_page_grid')->resize(298, 220)->getUrl();
						$_productNameStripped = $block->stripTags($_product->getName(), null, true);
						?>
						<div class="event-item-image">
							<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
								<img alt="<?= $_productNameStripped ?>" src="<?= $productImage ?>" class="product-event-photo"/>
							</a>
						</div>
						<div class="event-item-detail">
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
								</a>
							</strong>
							<div class="event-time">
								<?= strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')); ?>
							</div>
							<?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= substr(strip_tags($_helper->productAttribute($_product, $_product->getDescription(), 'description')), 0, 128); ?>...
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Read more') ?></a>
                                </div>
                            <?php endif; ?>
						</div>
					</div>
				</li>
			<?php endforeach ?>
		</ol>
	</div>
	<div class="bottom-toolbar">
        <?=$block->getToolbarHtml() ?>
    </div>
<?php endif ?>